"""Run trigger + progress + delta endpoints.

Flag-file pattern (decouples the dashboard from the collector — the dashboard
never runs the collection itself). The dashboard writes/reads flag files under
``runs/.trigger/`` on the shared ``runs/`` volume; a separate watcher process
polls for the request flag and executes ``netcopilot run`` wherever it has
network reach to the devices. This keeps the dashboard free of collection
dependencies (e.g. pyATS) and matches the "collector is not co-located"
deployment model.

Progress: writers append JSON lines to ``runs/.trigger/.progress.jsonl``:
  T=0   trigger_run() OVERWRITES with a "triggered" event
  T>0   the watcher APPENDS a "watcher_start" event
  T>0   ``netcopilot run`` APPENDS stage events (collect, parse, model, rules, load, done)
The dashboard tails the file over SSE → the frontend EventSource consumes it.

POST /api/runs/trigger   — create request flag + initial progress
GET  /api/runs/status    — run-in-progress state + latest run_id
GET  /api/runs/progress  — SSE stream tailing .progress.jsonl
GET  /api/runs/delta     — compare findings between two runs
"""

import asyncio
import json
import logging
import os
import shutil
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

log = logging.getLogger(__name__)
router = APIRouter()

RUNS_DIR = Path(os.environ.get("RUNS_DIR", "runs"))

# Flag files live inside the existing runs/ volume (shared with the watcher)
_TRIGGER_DIR = RUNS_DIR / ".trigger"
_FLAG_REQUESTED = _TRIGGER_DIR / "run_requested"
_FLAG_COMPLETE = _TRIGGER_DIR / "run_complete"
_FLAG_TRIGGERED_AT = _TRIGGER_DIR / "triggered_at"
_PROGRESS_FILE = _TRIGGER_DIR / ".progress.jsonl"
# The watcher reads this to know WHICH inventory to collect (or to replay the demo).
_FLAG_RUN_CONFIG = _TRIGGER_DIR / "run_config.json"

# Where operators drop their own inventory YAMLs (bind-mounted into the container).
_INVENTORY_DIR = Path(os.environ.get("NETCOPILOT_INVENTORY_DIR", "/app/inventory"))
# Bundled demo labs — each demo/<name>/ (facts + manifest) is replayed offline.
_DEMO_DIR = Path(os.environ.get("NETCOPILOT_DEMO_DIR", "/app/demo"))


def _demos_hidden() -> bool:
    """Production installs hide the bundled demo labs via NETCOPILOT_HIDE_DEMOS."""
    return os.environ.get("NETCOPILOT_HIDE_DEMOS", "").strip().lower() in ("1", "true", "yes", "on")


def _demo_inventories() -> list[dict]:
    """Each demo/<name>/ with committed facts is a replayable demo lab (its own
    site). Run Now on it rebuilds + loads offline — no devices needed. Hidden
    entirely when NETCOPILOT_HIDE_DEMOS is set (production deployments)."""
    if _demos_hidden():
        return []
    demos = []
    if _DEMO_DIR.is_dir():
        for sub in sorted(p for p in _DEMO_DIR.iterdir() if p.is_dir()):
            manifest = sub / "manifest.json"
            if not (sub / "facts").is_dir() or not manifest.is_file():
                continue
            try:
                m = json.loads(manifest.read_text())
            except (OSError, ValueError):
                continue
            demos.append({
                "id": sub.name,
                "label": m.get("demo_label", f"Demo — {sub.name} ({m.get('device_count', '?')} devices)"),
                "kind": "demo",
                "site": sub.name,
            })
    return demos


def _list_inventories() -> list[dict]:
    """Inventories selectable for 'Run Now': the bundled demo labs (offline
    replay) + any YAML files the operator dropped in the mounted inventory dir."""
    items = _demo_inventories()
    if _INVENTORY_DIR.is_dir():
        for f in sorted(_INVENTORY_DIR.glob("*.y*ml")):
            items.append({
                "id": f.stem, "label": f.stem, "kind": "real",
                "site": f.stem, "path": str(f),
            })
    return items


def _resolve_inventory(inv_id: str) -> dict | None:
    return next((i for i in _list_inventories() if i["id"] == inv_id), None)


class TriggerRequest(BaseModel):
    inventory_id: str = ""


def _ensure_trigger_dir() -> None:
    _TRIGGER_DIR.mkdir(parents=True, exist_ok=True)


@router.get("/api/inventories")
def list_inventories():
    """List selectable inventories for the Run Now picker."""
    return {"inventories": _list_inventories()}


@router.delete("/api/runs/{site}/{run_id}")
def delete_run_endpoint(site: str, run_id: str):
    """Delete a loaded run completely — graph data AND on-disk artifacts.

    Removes every Neo4j node for the run (DETACH DELETE) and the run's
    ``runs/<run_id>/`` directory (facts/raw/model/findings). Bundled demo
    *sources* live under ``demo/<name>/`` (never under ``runs/``), so a replayed
    demo run can always be regenerated by Run-Now after deletion.
    """
    from netcopilot.graph.client import get_driver
    from netcopilot.graph.loader import delete_run

    n = delete_run(get_driver(), run_id, site=site)

    # Also remove the on-disk run directory so the delete is complete, not just
    # graph-side. Guard against path traversal: only a bare run-id directory
    # located directly under RUNS_DIR is eligible for removal.
    dir_removed = False
    if run_id and "/" not in run_id and "\\" not in run_id and ".." not in run_id:
        run_dir = (RUNS_DIR / run_id).resolve()
        if run_dir.parent == RUNS_DIR.resolve() and run_dir.is_dir():
            shutil.rmtree(run_dir, ignore_errors=True)
            dir_removed = not run_dir.exists()

    return {"deleted": n > 0 or dir_removed, "nodes_deleted": n, "dir_removed": dir_removed}


@router.delete("/api/inventories/{inv_id}")
def delete_inventory(inv_id: str):
    """Delete a user inventory YAML file (the inventory-dropdown trashcan).
    Bundled demo labs cannot be deleted."""
    inv = _resolve_inventory(inv_id)
    if inv is None:
        raise HTTPException(status_code=404, detail=f"Unknown inventory '{inv_id}'")
    if inv["kind"] != "real":
        raise HTTPException(status_code=400, detail="Demo labs cannot be deleted")
    try:
        Path(inv["path"]).unlink()
    except OSError as e:
        raise HTTPException(status_code=500, detail=f"Could not delete inventory: {e}")
    return {"deleted": True, "id": inv_id}


def _latest_run_id() -> str | None:
    """Return the most recently modified run directory name, or None."""
    try:
        run_dirs = [
            d for d in RUNS_DIR.iterdir()
            if d.is_dir() and not d.name.startswith(".")
        ]
        if not run_dirs:
            return None
        latest = max(run_dirs, key=lambda d: d.stat().st_mtime)
        return latest.name
    except OSError:
        return None


@router.post("/api/runs/trigger")
def trigger_run(req: Optional[TriggerRequest] = None):
    """Create the run-requested flag + run_config for the watcher.

    The watcher reads ``run_config.json`` to know which inventory to collect — or,
    for the bundled demo, to replay the committed demo capture offline. Returns
    immediately; ``already_pending`` if a run is already in flight.
    """
    _ensure_trigger_dir()

    inv_id = req.inventory_id if req else ""
    if inv_id:
        inv = _resolve_inventory(inv_id)
        if inv is None:
            raise HTTPException(status_code=404, detail=f"Unknown inventory '{inv_id}'")
    else:
        avail = _list_inventories()
        if not avail:
            raise HTTPException(status_code=404, detail="No inventories available")
        inv = avail[0]

    # Clear a stale FLAG_COMPLETE from any earlier run whose completion was
    # never consumed by /api/runs/status (e.g. browser closed mid-poll).
    if _FLAG_COMPLETE.exists():
        try:
            _FLAG_COMPLETE.unlink()
        except OSError:
            pass

    if _FLAG_REQUESTED.exists():
        return {"status": "already_pending"}

    # Tell the watcher what to run: replay the demo, or collect a real inventory.
    if inv["kind"] == "demo":
        run_config = {"mode": "demo", "inventory": inv["id"], "site": inv["site"]}
    else:
        run_config = {"mode": "collect", "inventory": inv["path"], "site": inv["site"]}
    _FLAG_RUN_CONFIG.write_text(json.dumps(run_config))

    now = datetime.now(timezone.utc).isoformat()
    _FLAG_REQUESTED.write_text(now)
    _FLAG_TRIGGERED_AT.write_text(now)

    # Overwrite progress file with initial event (T=0, immediate feedback)
    _PROGRESS_FILE.write_text(
        json.dumps({"ts": now, "stage": "triggered",
                    "message": f"Run triggered for {inv['label']}…"}) + "\n"
    )

    log.info("Run requested at %s (inventory=%s mode=%s)", now, inv["id"], run_config["mode"])
    return {"status": "requested", "triggered_at": now, "inventory": inv["id"]}


@router.get("/api/runs/status")
def run_status():
    """Return current run status and latest run_id.

    Checks for the completion flag written by the watcher after a successful
    run. Clears the completion flag on read (one-shot notification).
    """
    run_in_progress = _FLAG_REQUESTED.exists()

    last_triggered = None
    try:
        last_triggered = _FLAG_TRIGGERED_AT.read_text().strip() or None
    except OSError:
        pass

    # Read and clear the completion flag (one-shot notification)
    new_run_available = False
    if _FLAG_COMPLETE.exists():
        try:
            _FLAG_COMPLETE.unlink()
            new_run_available = True
        except OSError:
            pass

    return {
        "run_in_progress": run_in_progress,
        "last_triggered": last_triggered,
        "latest_run_id": _latest_run_id(),
        "new_run_available": new_run_available,
    }


# ── Pipeline progress SSE ───────────────────────────────────────────────────────


@router.get("/api/runs/progress")
async def run_progress():
    """SSE stream tailing .progress.jsonl for real-time pipeline status.

    Writers append to the file: trigger_run() (T=0), the watcher
    (watcher_start), and ``netcopilot run`` (stage events). This endpoint
    tails it and streams events until 'done'/'error'.
    """
    return StreamingResponse(
        _stream_progress(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


async def _stream_progress():
    """Tail .progress.jsonl, yield SSE events. Close on 'done'/'error'."""
    lines_sent = 0
    start = time.monotonic()
    saw_watcher = False
    max_wait = 300  # 5 minutes

    while time.monotonic() - start < max_wait:
        # Read current file contents
        if _PROGRESS_FILE.exists():
            try:
                all_lines = _PROGRESS_FILE.read_text().strip().split("\n")
            except OSError:
                all_lines = []

            # Send new lines
            for line in all_lines[lines_sent:]:
                if not line.strip():
                    continue
                yield f"data: {line.strip()}\n\n"
                try:
                    parsed = json.loads(line.strip())
                    if parsed.get("stage") == "watcher_start":
                        saw_watcher = True
                    if parsed.get("stage") in ("done", "error"):
                        return
                except json.JSONDecodeError:
                    pass
            lines_sent = len(all_lines)

        # Dead-zone warning: 60s with no watcher_start
        elapsed = time.monotonic() - start
        if elapsed > 60 and not saw_watcher:
            warning = json.dumps({
                "ts": datetime.now(timezone.utc).isoformat(),
                "stage": "warning",
                "message": "Pipeline has not started after 60s. Is the run watcher running?",
            })
            yield f"data: {warning}\n\n"
            saw_watcher = True  # don't warn again

        await asyncio.sleep(1)

    yield f'data: {json.dumps({"ts": datetime.now(timezone.utc).isoformat(), "stage": "error", "message": "Progress timeout (5 min)"})}\n\n'


# ── Delta analysis ──────────────────────────────────────────────────────────────


@router.get("/api/runs/delta")
def get_delta(
    current: str = Query(..., description="Current run_id"),
    previous: Optional[str] = Query(None, description="Previous run_id — auto-selected if omitted"),
):
    """Compare findings between two runs.

    If previous is not specified, auto-selects the run immediately before
    current in chronological order.

    Returns:
        200: Delta dict with new/resolved/persistent findings and counts.
        404: current run not found, or no previous run available.
    """
    from netcopilot.dashboard.backend.delta_analyzer import build_delta, find_previous_run

    if not (RUNS_DIR / current).is_dir():
        raise HTTPException(status_code=404, detail=f"Run '{current}' not found")

    prev_run = previous or find_previous_run(current)
    if not prev_run:
        raise HTTPException(
            status_code=404,
            detail=f"No previous run found for '{current}'",
        )
    if not (RUNS_DIR / prev_run).is_dir():
        raise HTTPException(status_code=404, detail=f"Previous run '{prev_run}' not found")

    return build_delta(current, prev_run)
