"""
QoS Policy Parser — extract per-interface QoS data from Genie policy-map output.

Parses collected Genie output from:
  - ``show policy-map`` → genie_policy_map.json (policy definitions)
  - ``show policy-map interface`` → genie_policy_map_interface.json (counters)

and correlates them into a per-interface QoS dict::

    {
        "input": {
            "policy_name": "INGRESS-POLICER",
            "type": "policer",
            "cir_bps": 7500000000,
            "bc_bytes": 3750000,
            "conform_packets": 892341,
            "conform_bytes": 1189234112,
            "exceed_packets": 14523,
            "exceed_bytes": 19372544,
            "exceed_action": "drop"
        },
        "output": {
            "policy_name": "EGRESS-SHAPER",
            "type": "shaper",
            "cir_bps": 7500000000,
            "queue_drops": 0,
            "queue_depth": 0
        }
    }

Design Principles:
    - Two-pass correlation: definitions for type detection, interface data for counters
    - System policies (system-cpp-*) are excluded — not user-configured QoS
    - Missing fields → null (not every device/version provides all counters)
    - Policer vs shaper detected from Genie JSON structure, not policy name

Example::

    >>> from netcopilot.parse.cisco_native.qos import parse_qos_for_interfaces
    >>> qos_by_intf = parse_qos_for_interfaces(policy_map_data, policy_map_intf_data)
    >>> qos_by_intf["TwentyFiveGigE1/0/1"]["input"]["type"]
    'policer'
"""

import logging
from typing import Any

log = logging.getLogger(__name__)

# System-internal policy names to exclude from QoS enrichment. These are
# auto-generated by IOS XE for control-plane protection, not user-configured QoS.
SYSTEM_POLICY_PREFIXES = ("system-cpp-",)


# -------------------------------------------------------------------------
# Public API
# -------------------------------------------------------------------------

def parse_qos_for_interfaces(
    policy_map_data: dict[str, Any],
    policy_map_intf_data: dict[str, Any],
) -> dict[str, dict[str, Any]]:
    """
    Parse QoS data from Genie policy-map output into per-interface dicts.

    Correlates policy definitions (from ``show policy-map``) with per-interface
    operational counters (from ``show policy-map interface``) to produce a QoS
    dict for each interface that has an applied service-policy.

    Args:
        policy_map_data: Parsed output of ``show policy-map`` (Genie ShowPolicyMap).
            Structure: {"policy_map": {"<name>": {"class": {...}}, ...}}
        policy_map_intf_data: Parsed output of ``show policy-map interface``.
            Structure: {"<interface>": {"service_policy": {"input|output": {...}}}}

    Returns:
        Dict keyed by interface name → QoS data (input/output sub-dicts). Only
        interfaces with a service-policy are included (no entry = no QoS).
    """
    # Step 1: Build policy type map (policer vs shaper) from definitions
    policy_type_map = _parse_policy_definitions(policy_map_data)

    # Step 2: Parse per-interface QoS data
    result: dict[str, dict[str, Any]] = {}

    for intf_name, intf_data in policy_map_intf_data.items():
        service_policy = intf_data.get("service_policy")
        if not service_policy:
            continue

        intf_qos: dict[str, Any] = {}

        for direction in ("input", "output"):
            dir_data = service_policy.get(direction)
            if not dir_data:
                continue

            policy_names = dir_data.get("policy_name", {})
            if not policy_names:
                continue

            # Iterate over policy names applied in this direction
            # (typically one, but the schema allows multiple)
            for policy_name, policy_data in policy_names.items():
                if _is_system_policy(policy_name):
                    continue

                qos_entry = _extract_qos_from_interface_policy(
                    policy_name, policy_data, policy_type_map,
                )
                if qos_entry:
                    intf_qos[direction] = qos_entry

        if intf_qos:
            result[intf_name] = intf_qos

    log.debug("QoS parser: %d interfaces with QoS data", len(result))
    return result


# -------------------------------------------------------------------------
# Private helpers
# -------------------------------------------------------------------------

def _parse_policy_definitions(
    policy_map_data: dict[str, Any],
) -> dict[str, str]:
    """
    Build a mapping of policy name → type ("policer" or "shaper").

    Inspects each policy-map definition to determine if it contains a policer
    (police action) or shaper (shape/average_rate action). Unclassifiable
    policies are omitted.
    """
    result: dict[str, str] = {}

    policy_map = policy_map_data.get("policy_map", {})
    for policy_name, policy_info in policy_map.items():
        if _is_system_policy(policy_name):
            continue

        classes = policy_info.get("class", {})
        for _class_name, class_info in classes.items():
            if "police" in class_info:
                result[policy_name] = "policer"
                break
            # Shaper detection: shape_average_min / average_rate_traffic_shaping
            if class_info.get("average_rate_traffic_shaping") or class_info.get(
                "shape_average_min"
            ):
                result[policy_name] = "shaper"
                break

    log.debug(
        "QoS policy definitions: %s",
        ", ".join(f"{k}={v}" for k, v in sorted(result.items())),
    )
    return result


def _extract_qos_from_interface_policy(
    policy_name: str,
    policy_data: dict[str, Any],
    policy_type_map: dict[str, str],
) -> dict[str, Any] | None:
    """
    Extract QoS metrics from a single interface policy binding.

    Reads the class-map data for the primary class (typically class-default)
    and extracts policer or shaper counters.
    """
    class_maps = policy_data.get("class_map", {})
    if not class_maps:
        return None

    # Use the first class-map (typically "class-default" for simple policies).
    for class_name, class_data in class_maps.items():
        police_data = class_data.get("police")
        if police_data:
            return _extract_policer_data(policy_name, police_data, policy_type_map)

        # Shaper data: shape_cir_bps presence (or queueing) indicates a shaper
        if class_data.get("shape_cir_bps") is not None or class_data.get("queueing"):
            return _extract_shaper_data(policy_name, class_data, policy_type_map)

    return None


def _extract_policer_data(
    policy_name: str,
    police_data: dict[str, Any],
    policy_type_map: dict[str, str],
) -> dict[str, Any]:
    """
    Extract policer metrics from interface police data.

    Genie police structure::
        {"cir_bps": N, "cir_bc_bytes": N,
         "conformed": {"packets": N, "bytes": N, "actions": {...}},
         "exceeded": {"packets": N, "bytes": N, "actions": {...}},
         "violated": {...}}
    """
    conformed = police_data.get("conformed", {})
    exceeded = police_data.get("exceeded", {})

    exceed_action = _extract_action(exceeded.get("actions", {}))

    # bc_bytes: some IOS XE versions use "pir_bc_bytes" instead of "cir_bc_bytes"
    bc_bytes = police_data.get("cir_bc_bytes") or police_data.get("pir_bc_bytes")

    return {
        "policy_name": policy_name,
        "type": policy_type_map.get(policy_name, "policer"),
        "cir_bps": police_data.get("cir_bps") or police_data.get("rate_bps"),
        "bc_bytes": bc_bytes,
        "conform_packets": conformed.get("packets"),
        "conform_bytes": conformed.get("bytes"),
        "exceed_packets": exceeded.get("packets"),
        "exceed_bytes": exceeded.get("bytes"),
        "exceed_action": exceed_action,
    }


def _extract_shaper_data(
    policy_name: str,
    class_data: dict[str, Any],
    policy_type_map: dict[str, str],
) -> dict[str, Any]:
    """
    Extract shaper metrics from interface class-map data.

    Genie shaper structure (class-map level)::
        {"shape_cir_bps": N, "shape_bc_bps": N, "target_shape_rate": N,
         "queue_depth": 0, "total_drops": 0, "pkts_output": N, "bytes_output": N}
    """
    # conform_packets: prefer "pkts_output", fall back to class-level "packets"
    conform_packets = class_data.get("pkts_output") or class_data.get("packets")

    return {
        "policy_name": policy_name,
        "type": policy_type_map.get(policy_name, "shaper"),
        "cir_bps": class_data.get("shape_cir_bps") or class_data.get(
            "target_shape_rate"
        ),
        "queue_drops": class_data.get("total_drops"),
        "queue_depth": class_data.get("queue_depth"),
        "conform_packets": conform_packets,
        "conform_bytes": class_data.get("bytes_output"),
    }


def _extract_action(actions: dict[str, Any]) -> str | None:
    """
    Extract the primary action string from a Genie actions dict.

    Actions dict has the form {"transmit": true}, {"drop": true}, or
    {"set-dscp-transmit": "af11"}. Returns the first truthy action name, or None.
    """
    if not actions:
        return None
    for action_name, action_val in actions.items():
        if action_val:
            return action_name
    return None


def _is_system_policy(policy_name: str) -> bool:
    """
    Check if a policy name is a system-internal policy (e.g. system-cpp-policy),
    auto-generated by IOS XE for control-plane protection — excluded from QoS.
    """
    return any(policy_name.startswith(prefix) for prefix in SYSTEM_POLICY_PREFIXES)
